# -*- coding: utf-8 -*-
"""Weekend Getaway Ranker.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11JZFlPzZEDDTMZq3Z4k1uqhfoXwA3nhF
"""

import pandas as pd

# Load dataset
df = pd.read_csv("/content/Top Indian Places to Visit.csv")

# Select required columns
df = df[[
    'City',
    'Name',
    'time needed to visit in hrs',
    'Google review rating',
    'Entrance Fee in INR',
    'Airport with 50km Radius',
    'Weekly Off',
    'Significance',
    'DSLR Allowed',
    'Number of google review in lakhs',
    'Best Time to visit'
]]

# User input
source_city = input("Enter Source City: ")

# Filter out same city destinations
destinations = df[df['City'] != source_city].copy()

# -------------------------------
# Feature Engineering
# -------------------------------

# Time score (lower time = higher score)
destinations['Time Score'] = 1 / destinations['time needed to visit in hrs']

# Cost score (lower fee = higher score)
destinations['Cost Score'] = 1 / (destinations['Entrance Fee in INR'] + 1)

# Airport accessibility
destinations['Airport Score'] = destinations['Airport with 50km Radius'].apply(
    lambda x: 1 if x == 'Yes' else 0
)

# DSLR allowed bonus
destinations['DSLR Score'] = destinations['DSLR Allowed'].apply(
    lambda x: 1 if x == 'Yes' else 0
)

# -------------------------------
# Final Score Calculation
# -------------------------------

destinations['Final Score'] = (
    0.35 * destinations['Google review rating'] +
    0.35 * destinations['Number of google review in lakhs'] +
    0.15 * destinations['Time Score'] +
    0.10 * destinations['Cost Score'] +
    0.05 * destinations['Airport Score']
)

# Sort results
top_destinations = destinations.sort_values(
    by='Final Score', ascending=False
).head(5)

# Display output
print("\nTop Weekend Destinations:\n")
display(top_destinations[[
    'Name',
    'City',
    'time needed to visit in hrs',
    'Google review rating',
    'Entrance Fee in INR',
    'Number of google review in lakhs',
    'Airport with 50km Radius',
    'DSLR Allowed',
    'Best Time to visit',
    'Final Score'
]])